## Data Cleaning/Interpretation

In [1]:
import pandas as pd

movies = pd.read_csv("data/tmdb_movies.csv")

print("Rows and columns:", movies.shape)
print("Duplicate movie IDs:", movies["tmdb_id"].duplicated().sum())

audit = pd.DataFrame({
    "data_type": movies.dtypes,
    "missing": movies.isna().sum(),
    "missing_pct": movies.isna().mean().mul(100).round(1)
})
display(audit)

print("Zero budgets:", movies["budget"].eq(0).sum())
print("Zero revenues:", movies["revenue"].eq(0).sum())
print("Zero runtimes:", movies["runtime"].eq(0).sum())

display(
    movies[
        ["budget", "revenue", "runtime", "vote_average", "vote_count"]
    ].describe()
)

Rows and columns: (5500, 15)
Duplicate movie IDs: 0

                     data_type  missing  missing_pct
tmdb_id                  int64        0          0.0
imdb_id                    str        2          0.0
title                      str        0          0.0
release_date               str        0          0.0
budget                   int64        0          0.0
revenue                  int64        0          0.0
runtime                  int64        0          0.0
genres                     str        0          0.0
original_language          str        0          0.0
popularity             float64        0          0.0
production_companies       str       34          0.6
director                   str        1          0.0
top_cast                   str       13          0.2
vote_count               int64        0          0.0
vote_average           float64        0          0.0

Zero budgets: 1987
Zero revenues: 1704
Zero runtimes: 2

             budget       revenue      runtime  vote_average    vote_count
count  5.500000e+03  5.500000e+03  5500.000000   5500.000000   5500.000000
mean   1.788425e+07  4.378408e+07   103.316364      6.408027   1331.009091
std    2.819694e+07  1.038828e+08    24.102450      0.822632   2808.932739
min    0.000000e+00  0.000000e+00     0.000000      2.800000    100.000000
25%    0.000000e+00  0.000000e+00    92.000000      5.900000    177.000000
50%    5.550000e+06  6.500000e+06   101.000000      6.500000    377.000000
75%    2.500000e+07  3.773247e+07   113.000000      7.000000   1158.000000
max    3.000000e+08  2.264162e+09   432.000000      8.752000  33145.000000

vhj